server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DmitrinAv/cloudconfig.git
        encrypt:
          enabled: false

security:
  basic:
    enabled: false
  user:
    name: root
    password: root

encrypt:
  key: testKey
